stages:
  data_ingestion:
    cmd : python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Oral Cancer Image Dataset

  prepare_base_model:
    cmd : python src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - CLASSES
      - INCLUDE_TOP
      - WEIGHTS
      - LEARNING_RATE
    outs :
      - artifacts/prepare_base_model

  training:
    cmd : python src/cnnClassifier/pipeline/stage_03_model_training.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/prepare_base_model
      - artifacts/data_ingestion/Oral Cancer Image Dataset
    params:
      - IMAGE_SIZE
      - EPOCHS
      - AUGMENTATION
      - BATCH_SIZE
    outs:
      - artifacts/training/model.keras  

  evaluation:
    cmd : python src/cnnClassifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/training/model.keras
      - artifacts/data_ingestion/Oral Cancer Image Dataset

    params:
      - IMAGE_SIZE
      - BATCH_SIZE

    metrics:
      - scores.json:
          cache: false
